// Generated by CoffeeScript 1.12.6
(function() {
  if (location.host !== "127.0.0.1" && location.protocol === "http:") {
    location.href = location.href.replace("http://", "https://");
  }

}).call(this);
